#!/usr/bin/env ansible-playbook
---
# See README.md for usage

# Tasks for all hosts
- hosts: all
  remote_user: ansible
  become: true

  roles:
    - role: firewall
    - role: user
    - role: nebula-lighthouse
