---
- name: Start firewalld
  service:
    name: firewalld
    state: started
    enabled: yes

- name: Start ufw
  service:
    name: ufw
    state: started
    enabled: yes

- name: Reload ufw
  ufw:
    state: reloaded